---
    - name: Failing if authorization is not properly configured
      fail:
        msg: "You did not set fame_user and fame_password in your configuration. This is required for fame_align to work! If you do not have the credentials yet, contact h.vandenheuvel@let.ru.nl to request access."
      when: fame_user == "undefined" or fame_password == "undefined"

    - name: Installing webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           github_user: "schemreier"
           github_repo: "frisianalign" #github repo is named differently than the python module
           metadata:
              identifier: "fame_align"

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - clam
        - fame_align

    - name: Removing old resources (if present)
      file:
          path: "{{lm_prefix}}/opt/fame_align_resources"
          state: absent
      ignore_errors: yes #in case it isn't there in the first place

    - name: Creating directory for resources
      become: "{{lm_become}}"
      become_user: root
      file:
          path: "{{lm_prefix}}/opt/fame_align_resources"
          state: directory
          owner: "{{unix_user}}"
          group: "{{unix_group}}"
          mode: u+rwx,g+rwsx,a+rx

    - name: Downloading resources
      get_url:
        url: https://applejack.science.ru.nl/downloads/fame/fame_align/fame_align_resources.tar.gz
        url_username: "{{fame_user}}"
        url_password: "{{fame_password}}"
        dest: "{{lm_prefix}}/opt/fame_align_resources/fame_align_resources.tar.gz"
        tmp_dest: "{{lm_prefix}}/opt/fame_align_resources"


    - name: Finalising resource installation
      shell: |
          #!/bin/bash
          tar xzf fame_align_resources.tar.gz
          rm -rf fame_align_resources.tar.gz
          mv resources/* .
          chown -R {{unix_user}}:{{unix_group}} .
          find . -type d | xargs chmod u+rw,g+rw,a+rx
          find . -type f | xargs chmod u+rw,g+rw,a+r
      args:
          chdir: "{{lm_prefix}}/opt/fame_align_resources"

    - name: Installing fame_align web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: fame_align
          clam: fame_align
          uwsgi: fame_align

    - name: Register webservice metadata
      include_role:
          name: lamachine-register
      vars:
          update: "{{item}}"
          metadata: #add entrypoint metadata to registry
              identifier: "{{item}}"
              entryPoints:
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "WUI", mediatorApplication: "#fame_align" }
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "REST", specification: "{{lm_base_url}}/{{item}}/info",  mediatorApplication: "#fame_aligh" }
      when: '"all" in services or item in services'
      with_items:
        - fame_align


