{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8801
urlprefix: "frog"
root: "{{www_data_path}}/frog.clam/"
bindir: "{{lm_prefix}}/bin/"
{% if "switchboard" in remote_services and remote_services.switchboard %}
switchboard_forward_url: "{{remote_services.switchboard}}/#/frog/$BACKLINK/$MIMETYPE/nld"
{% endif %}
